# This is a basic workflow to help you get started with Actions

name: CICD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions  tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo application build successfull
      - run: echo "${GITHUB_REF}"
          
  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: [build]
    environment: dev
    steps:
      - run: echo deployed metrics site to dev environment
      - run: echo deployed tableau sync service to dev environment
      - run: echo deployed double click extract service to dev environment
      - run: echo deployed extract control service to dev environment
          
  deploy-to-stage:
    runs-on: ubuntu-latest
    needs: [deploy-to-dev]
    environment: staging
    steps:
      - run: echo deployed metrics site to staging environment
      - run: echo deployed tableau sync service to staging environment
      - run: echo deployed double click extract service to staging environment
      - run: echo deployed extract control service to staging environment
          
  deploy-2-to-stage:
    runs-on: ubuntu-latest
    needs: [deploy-to-dev]
    environment: staging
    steps:
      - run: echo deployed metrics site to staging environment
      - run: echo deployed tableau sync service to staging environment
      - run: echo deployed double click extract service to staging environment
      - run: echo deployed extract control service to staging environment
          
  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: [deploy-to-stage]
    environment: production
    steps:
      - run: echo deployed metrics site to prod environment
      - run: echo deployed tableau sync service to prod environment
      - run: echo deployed double click extract service to prod environment
      - run: echo deployed extract control service to prod environment
